// web/frontend/src/pages/admin/DashboardTab.tsx
import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {adminApi} from '@/api/endpoints'
import type {StreamSession, UploadProgress} from '@/api/types'
import {errMsg, formatBytes, formatUptime} from './adminUtils'

export function DashboardTab() {
    const [actionMsg, setActionMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null)

    const {data: stats, isLoading: statsLoading} = useQuery({
        queryKey: ['admin-stats'],
        queryFn: () => adminApi.getStats(),
        refetchInterval: 30000,
    })

    const {data: system, isLoading: sysLoading} = useQuery({
        queryKey: ['admin-system'],
        queryFn: () => adminApi.getSystemInfo(),
        refetchInterval: 60000,
    })

    const {data: activeStreams = [], isError: streamsError} = useQuery<StreamSession[]>({
        queryKey: ['admin-active-streams'],
        queryFn: () => adminApi.getActiveStreams(),
        refetchInterval: 10000,
        retry: 1,
    })

    const {data: activeUploads = [], isError: uploadsError} = useQuery<UploadProgress[]>({
        queryKey: ['admin-active-uploads'],
        queryFn: () => adminApi.getActiveUploads(),
        refetchInterval: 10000,
        retry: 1,
    })

    async function handleAction(fn: () => Promise<unknown>, successMsg: string) {
        setActionMsg(null)
        try {
            await fn()
            setActionMsg({type: 'success', text: successMsg})
        } catch (err: unknown) {
            setActionMsg({type: 'error', text: errMsg(err)})
        }
    }

    const diskPct = stats ? Math.round(((stats.disk_usage ?? 0) / ((stats.disk_total ?? 0) || 1)) * 100) : 0
    const memPct = system ? Math.round(((system.memory_used ?? 0) / ((system.memory_total ?? 0) || 1)) * 100) : 0
    let diskFillClass = ''
    if (diskPct > 90) diskFillClass = 'danger'
    else if (diskPct > 70) diskFillClass = 'warning'

    return (
        <div>
            {actionMsg && (
                <div className={`admin-alert admin-alert-${actionMsg.type === 'success' ? 'success' : 'danger'}`}>
                    {actionMsg.text}
                </div>
            )}

            {statsLoading ? (
                <p style={{color: 'var(--text-muted)'}}>Loading statistics...</p>
            ) : stats && (
                <>
                    <div className="admin-stats-grid">
                        <div className="admin-stat-card">
                            <span className="admin-stat-value">{(stats.total_videos ?? 0).toLocaleString()}</span>
                            <span className="admin-stat-label">Videos</span>
                        </div>
                        <div className="admin-stat-card">
                            <span className="admin-stat-value">{(stats.total_audio ?? 0).toLocaleString()}</span>
                            <span className="admin-stat-label">Audio Files</span>
                        </div>
                        <div className="admin-stat-card">
                            <span className="admin-stat-value">{(stats.total_users ?? 0).toLocaleString()}</span>
                            <span className="admin-stat-label">Total Users</span>
                        </div>
                        <div className="admin-stat-card">
                            <span className="admin-stat-value">{(stats.active_sessions ?? 0).toLocaleString()}</span>
                            <span className="admin-stat-label">Active Streams</span>
                        </div>
                        <div className="admin-stat-card">
                            <span className="admin-stat-value">{(stats.total_views ?? 0).toLocaleString()}</span>
                            <span className="admin-stat-label">Total Views</span>
                        </div>
                        <div className="admin-stat-card">
                            <span className="admin-stat-value">{stats.hls_jobs_running ?? 0}</span>
                            <span className="admin-stat-label">HLS Running</span>
                        </div>
                        <div className="admin-stat-card">
                            <span className="admin-stat-value">{stats.hls_jobs_completed ?? 0}</span>
                            <span className="admin-stat-label">HLS Completed</span>
                        </div>
                    </div>

                    <div className="admin-card">
                        <h2>Storage</h2>
                        <div>
                            <div style={{
                                display: 'flex',
                                justifyContent: 'space-between',
                                fontSize: 13,
                                marginBottom: 4
                            }}>
                                <span>Disk Usage</span>
                                <span>{formatBytes(stats.disk_usage ?? 0)} / {formatBytes(stats.disk_total ?? 0)}</span>
                            </div>
                            <div className="disk-usage-bar">
                                <div
                                    className={`disk-usage-fill ${diskFillClass}`}
                                    style={{width: `${diskPct}%`}}
                                />
                            </div>
                            <div style={{fontSize: 12, color: 'var(--text-muted)', marginTop: 4}}>
                                {diskPct}% used · {formatBytes(stats.disk_free ?? 0)} free
                            </div>
                        </div>
                    </div>

                    <div className="admin-card">
                        <h2>Live streams</h2>
                        <p style={{fontSize: 12, color: 'var(--text-muted)', margin: '0 0 10px'}}>
                            Concurrent playback sessions (refreshes every 10s). Matches the “Active Streams” total above when all are counted server-side.
                        </p>
                        {streamsError ? (
                            <p style={{color: 'var(--text-muted)', fontSize: 13}}>Could not load active streams.</p>
                        ) : activeStreams.length === 0 ? (
                            <p style={{color: 'var(--text-muted)', fontSize: 13}}>No active streams.</p>
                        ) : (
                            <div className="admin-table-wrapper">
                                <table className="admin-table">
                                    <thead>
                                    <tr>
                                        <th>User</th>
                                        <th>Media ID</th>
                                        <th>Quality</th>
                                        <th>Sent</th>
                                        <th>Client IP</th>
                                        <th>Since</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {activeStreams.map(s => (
                                        <tr key={s.id}>
                                            <td style={{fontSize: 12}}>{s.user_id || '—'}</td>
                                            <td style={{fontSize: 11, fontFamily: 'monospace'}} title={s.media_id}>
                                                {s.media_id && s.media_id.length > 8 ? `${s.media_id.slice(0, 8)}…` : (s.media_id || '—')}
                                            </td>
                                            <td>{s.quality || '—'}</td>
                                            <td>{formatBytes(s.bytes_sent ?? 0)}</td>
                                            <td style={{fontSize: 12}}>{s.ip_address || '—'}</td>
                                            <td style={{fontSize: 12}}>{new Date(s.started_at).toLocaleString()}</td>
                                        </tr>
                                    ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </div>

                    <div className="admin-card">
                        <h2>Active uploads</h2>
                        {uploadsError ? (
                            <p style={{color: 'var(--text-muted)', fontSize: 13}}>Could not load active uploads.</p>
                        ) : activeUploads.length === 0 ? (
                            <p style={{color: 'var(--text-muted)', fontSize: 13}}>No uploads in progress.</p>
                        ) : (
                            <div className="admin-table-wrapper">
                                <table className="admin-table">
                                    <thead>
                                    <tr>
                                        <th>File</th>
                                        <th>User</th>
                                        <th>Progress</th>
                                        <th>Status</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {activeUploads.map(u => (
                                        <tr key={u.id}>
                                            <td style={{fontSize: 12}}>{u.filename}</td>
                                            <td style={{fontSize: 12}}>{u.user_id || '—'}</td>
                                            <td>{typeof u.progress === 'number' ? `${Math.round(u.progress)}%` : '—'}</td>
                                            <td>{u.status}</td>
                                        </tr>
                                    ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </div>
                </>
            )}

            {!sysLoading && system && (
                <div className="admin-card">
                    <h2>System Info</h2>
                    <div style={{
                        display: 'grid',
                        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
                        gap: 12,
                        marginBottom: 16
                    }}>
                        <div><strong>Version:</strong> {typeof system.version === 'string' ? system.version : '—'}</div>
                        <div><strong>OS:</strong> {system.os}/{system.arch}</div>
                        <div><strong>Go:</strong> {typeof system.go_version === 'string' ? system.go_version : '—'}</div>
                        <div><strong>Uptime:</strong> {formatUptime(system.uptime)}</div>
                        <div><strong>CPUs:</strong> {system.cpu_count}</div>
                        <div>
                            <strong>Memory:</strong> {formatBytes(system.memory_used)} / {formatBytes(system.memory_total)}
                            <div className="admin-progress-bg" style={{marginTop: 4}}>
                                <div className="admin-progress-fill" style={{width: `${memPct}%`}}/>
                            </div>
                        </div>
                    </div>
                    {system.modules?.length > 0 && (
                        <>
                            <h3 style={{margin: '0 0 10px'}}>Module Health</h3>
                            <div className="module-health-grid">
                                {system.modules.map(m => (
                                    <div key={m.name} className="module-health-item">
                                        <span className="module-health-name">{m.name}</span>
                                        <span className={`status-badge status-${m.status}`}>{m.status}</span>
                                    </div>
                                ))}
                            </div>
                        </>
                    )}
                </div>
            )}

            <div className="admin-card">
                <h2>Server Controls</h2>
                <div className="admin-action-row">
                    <button className="admin-btn"
                            onClick={() => handleAction(() => adminApi.clearCache(), 'Cache cleared')}>
                        <i className="bi bi-trash-fill"/> Clear Cache
                    </button>
                    <button className="admin-btn"
                            onClick={() => handleAction(() => adminApi.scanMedia(), 'Media scan triggered')}>
                        <i className="bi bi-search"/> Scan Media
                    </button>
                    <button className="admin-btn admin-btn-warning" onClick={() => {
                        if (window.confirm('Restart the server? Active streams will be interrupted.')) {
                            handleAction(() => adminApi.restartServer(), 'Server restarting… page will reload in 10s')
                            setTimeout(() => { window.location.reload(); }, 10000)
                        }
                    }}>
                        <i className="bi bi-arrow-clockwise"/> Restart Server
                    </button>
                    <button className="admin-btn admin-btn-danger" onClick={() => {
                        if (window.confirm('Shut down the server?'))
                            handleAction(() => adminApi.shutdownServer(), 'Server shutting down...')
                    }}>
                        <i className="bi bi-power"/> Shutdown
                    </button>
                </div>
            </div>
        </div>
    )
}

// web/nuxt-ui/components/admin/DashboardTab.vue
<script setup lang="ts">
import type { AdminStats, SystemInfo, StreamSession, UploadProgress, ModuleHealth, ServerSettings } from '~/types/api'

const adminApi = useAdminApi()
const settingsApi = useSettingsApi()
const toast = useToast()

const settings = ref<ServerSettings | null>(null)

const stats = ref<AdminStats | null>(null)
const system = ref<SystemInfo | null>(null)
const streams = ref<StreamSession[]>([])
const uploads = ref<UploadProgress[]>([])
const statsLoading = ref(true)

function formatBytes(bytes: number): string {
  if (!bytes) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${(bytes / k ** i).toFixed(1)} ${sizes[i]}`
}

function formatUptime(secs: number): string {
  if (!secs) return '—'
  const d = Math.floor(secs / 86400)
  const h = Math.floor((secs % 86400) / 3600)
  const m = Math.floor((secs % 3600) / 60)
  return d > 0 ? `${d}d ${h}h ${m}m` : h > 0 ? `${h}h ${m}m` : `${m}m`
}

const diskPct = computed(() => {
  if (!stats.value) return 0
  return Math.round(((stats.value.disk_usage ?? 0) / ((stats.value.disk_total || 1))) * 100)
})
const diskColor = computed(() => diskPct.value > 90 ? 'error' : diskPct.value > 70 ? 'warning' : 'success')

const memPct = computed(() => {
  if (!system.value) return 0
  return Math.round(((system.value.memory_used ?? 0) / ((system.value.memory_total || 1))) * 100)
})

function moduleStatusColor(status: ModuleHealth['status']) {
  return status === 'healthy' ? 'success' : status === 'degraded' ? 'warning' : 'error'
}

async function loadAll() {
  statsLoading.value = true
  try {
    const [s, sys, str, upl, sett] = await Promise.allSettled([
      adminApi.getStats(),
      adminApi.getSystemInfo(),
      adminApi.getActiveStreams(),
      adminApi.getActiveUploads(),
      settingsApi.get(),
    ])
    if (s.status === 'fulfilled') stats.value = s.value
    if (sys.status === 'fulfilled') system.value = sys.value
    if (str.status === 'fulfilled') streams.value = str.value ?? []
    if (upl.status === 'fulfilled') uploads.value = upl.value ?? []
    if (sett.status === 'fulfilled') settings.value = sett.value
  } finally {
    statsLoading.value = false
  }
}

async function handleAction(fn: () => Promise<unknown>, successMsg: string) {
  try {
    await fn()
    toast.add({ title: successMsg, color: 'success', icon: 'i-lucide-check' })
  } catch (e: unknown) {
    toast.add({ title: e instanceof Error ? e.message : 'Action failed', color: 'error', icon: 'i-lucide-x' })
  }
}

onMounted(loadAll)
// Auto-refresh every 30s
const interval = setInterval(loadAll, 30_000)
onUnmounted(() => clearInterval(interval))
</script>

<template>
  <div class="space-y-6">
    <!-- Loading -->
    <div v-if="statsLoading && !stats" class="flex justify-center py-12">
      <UIcon name="i-lucide-loader-2" class="animate-spin size-8 text-primary" />
    </div>

    <template v-else-if="stats">
      <!-- Stat cards -->
      <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-7 gap-3">
        <UCard
          v-for="item in [
            { label: 'Videos', value: stats.total_videos ?? 0, icon: 'i-lucide-film' },
            { label: 'Audio', value: stats.total_audio ?? 0, icon: 'i-lucide-music' },
            { label: 'Users', value: stats.total_users ?? 0, icon: 'i-lucide-users' },
            { label: 'Sessions', value: stats.active_sessions ?? 0, icon: 'i-lucide-activity' },
            { label: 'Views', value: stats.total_views ?? 0, icon: 'i-lucide-eye' },
            { label: 'HLS Running', value: stats.hls_jobs_running ?? 0, icon: 'i-lucide-radio' },
            { label: 'HLS Done', value: stats.hls_jobs_completed ?? 0, icon: 'i-lucide-check-circle' },
          ]"
          :key="item.label"
          :ui="{ body: 'p-4' }"
        >
          <div class="flex items-start gap-2">
            <UIcon :name="item.icon" class="size-4 text-muted mt-0.5" />
            <div>
              <p class="text-xl font-bold text-highlighted">{{ item.value.toLocaleString() }}</p>
              <p class="text-xs text-muted">{{ item.label }}</p>
            </div>
          </div>
        </UCard>
      </div>

      <!-- Disk -->
      <UCard>
        <template #header>
          <div class="flex items-center gap-2 font-semibold">
            <UIcon name="i-lucide-hard-drive" class="size-4" />
            Storage
          </div>
        </template>
        <div class="space-y-2">
          <div class="flex justify-between text-sm">
            <span class="text-muted">Disk Usage</span>
            <span>{{ formatBytes(stats.disk_usage ?? 0) }} / {{ formatBytes(stats.disk_total ?? 0) }}</span>
          </div>
          <UProgress :value="diskPct" :color="diskColor" size="sm" />
          <p class="text-xs text-muted">{{ diskPct }}% used · {{ formatBytes(stats.disk_free ?? 0) }} free</p>
        </div>
      </UCard>

      <!-- Live streams -->
      <UCard>
        <template #header>
          <div class="flex items-center gap-2 font-semibold">
            <UIcon name="i-lucide-radio" class="size-4" />
            Live Streams
            <UBadge :label="String(streams.length)" color="neutral" variant="subtle" size="xs" />
          </div>
        </template>
        <p v-if="streams.length === 0" class="text-muted text-sm">No active streams.</p>
        <UTable
          v-else
          :data="streams"
          :columns="[
            { accessorKey: 'user_id', header: 'User' },
            { accessorKey: 'media_id', header: 'Media ID' },
            { accessorKey: 'quality', header: 'Quality' },
            { accessorKey: 'bytes_sent', header: 'Sent' },
            { accessorKey: 'ip_address', header: 'Client IP' },
            { accessorKey: 'started_at', header: 'Since' },
          ]"
          class="text-sm"
        >
          <template #media_id-cell="{ row }">
            <span class="font-mono text-xs" :title="row.original.media_id">
              {{ row.original.media_id?.slice(0, 8) }}…
            </span>
          </template>
          <template #bytes_sent-cell="{ row }">
            {{ formatBytes(row.original.bytes_sent ?? 0) }}
          </template>
          <template #started_at-cell="{ row }">
            {{ new Date(row.original.started_at).toLocaleTimeString() }}
          </template>
        </UTable>
      </UCard>

      <!-- Uploads -->
      <UCard v-if="uploads.length > 0">
        <template #header>
          <div class="flex items-center gap-2 font-semibold">
            <UIcon name="i-lucide-upload" class="size-4" />
            Active Uploads
          </div>
        </template>
        <UTable
          :data="uploads"
          :columns="[
            { accessorKey: 'filename', header: 'File' },
            { accessorKey: 'user_id', header: 'User' },
            { accessorKey: 'progress', header: 'Progress' },
            { accessorKey: 'status', header: 'Status' },
          ]"
          class="text-sm"
        >
          <template #progress-cell="{ row }">
            {{ row.original.progress != null ? `${Math.round(row.original.progress)}%` : '—' }}
          </template>
        </UTable>
      </UCard>
    </template>

    <!-- System info -->
    <UCard v-if="system">
      <template #header>
        <div class="flex items-center gap-2 font-semibold">
          <UIcon name="i-lucide-cpu" class="size-4" />
          System Info
        </div>
      </template>
      <div class="grid grid-cols-2 sm:grid-cols-3 gap-4 text-sm mb-4">
        <div><span class="text-muted">Version:</span> <span class="font-mono">{{ system.version }}</span></div>
        <div><span class="text-muted">OS/Arch:</span> {{ system.os }}/{{ system.arch }}</div>
        <div><span class="text-muted">Go:</span> {{ system.go_version }}</div>
        <div><span class="text-muted">Uptime:</span> {{ formatUptime(system.uptime) }}</div>
        <div><span class="text-muted">CPUs:</span> {{ system.cpu_count }}</div>
        <div>
          <span class="text-muted">Memory:</span>
          {{ formatBytes(system.memory_used) }} / {{ formatBytes(system.memory_total) }}
          <UProgress :value="memPct" size="xs" class="mt-1" />
        </div>
      </div>
      <div v-if="system.modules?.length" class="space-y-1">
        <p class="text-sm font-medium text-highlighted mb-2">Module Health</p>
        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          <div
            v-for="m in system.modules"
            :key="m.name"
            class="flex items-center justify-between text-xs bg-muted rounded px-2 py-1"
          >
            <span class="text-muted truncate">{{ m.name }}</span>
            <UBadge :label="m.status" :color="moduleStatusColor(m.status)" size="xs" variant="subtle" />
          </div>
        </div>
      </div>
    </UCard>

    <!-- Features panel -->
    <UCard v-if="settings">
      <template #header>
        <div class="flex items-center gap-2 font-semibold">
          <UIcon name="i-lucide-toggle-right" class="size-4" />
          Feature Flags
        </div>
      </template>
      <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
        <div
          v-for="[name, enabled] in Object.entries(settings.features)"
          :key="name"
          class="flex items-center justify-between text-xs rounded px-2 py-1.5"
          :class="enabled ? 'bg-success/10' : 'bg-muted'"
        >
          <span class="text-muted truncate">{{ name.replace(/^enable/, '').replace(/([A-Z])/g, ' $1').trim() }}</span>
          <UIcon :name="enabled ? 'i-lucide-check' : 'i-lucide-minus'" :class="enabled ? 'text-success' : 'text-muted'" class="size-3 shrink-0 ml-1" />
        </div>
      </div>
    </UCard>

    <!-- Server controls -->
    <UCard>
      <template #header>
        <div class="flex items-center gap-2 font-semibold">
          <UIcon name="i-lucide-settings-2" class="size-4" />
          Server Controls
        </div>
      </template>
      <div class="flex flex-wrap gap-2">
        <UButton
          icon="i-lucide-trash-2"
          label="Clear Cache"
          variant="outline"
          color="neutral"
          @click="handleAction(adminApi.clearCache, 'Cache cleared')"
        />
        <UButton
          icon="i-lucide-scan"
          label="Scan Media"
          variant="outline"
          color="neutral"
          @click="handleAction(adminApi.scanMedia, 'Media scan triggered')"
        />
        <UButton
          icon="i-lucide-rotate-cw"
          label="Restart Server"
          variant="outline"
          color="warning"
          @click="handleAction(adminApi.restartServer, 'Server restarting…')"
        />
        <UButton
          icon="i-lucide-power"
          label="Shutdown"
          variant="outline"
          color="error"
          @click="handleAction(adminApi.shutdownServer, 'Server shutting down…')"
        />
      </div>
    </UCard>
  </div>
</template>
