// web/frontend/src/pages/admin/PlaylistsTab.tsx
import {useState} from 'react'
import {useQuery, useQueryClient} from '@tanstack/react-query'
import {adminApi} from '@/api/endpoints'
import type {AdminPlaylistStats, Playlist} from '@/api/types'
import {errMsg} from './adminUtils'

// ── Tab: Playlists (Feature 6) ────────────────────────────────────────────────

type PlaylistSortKey = 'name' | 'user_id' | 'items' | 'created_at' | 'is_public'

const PLAYLIST_SORT_COLUMNS: ReadonlyArray<{key: PlaylistSortKey; label: string}> = [
    {key: 'name', label: 'Name'},
    {key: 'user_id', label: 'Owner'},
    {key: 'items', label: 'Items'},
    {key: 'is_public', label: 'Public'},
    {key: 'created_at', label: 'Created'},
]

export function PlaylistsTab() {
    const queryClient = useQueryClient()
    const [msg, setMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null)
    const [search, setSearch] = useState('')
    const [selected, setSelected] = useState<Set<string>>(new Set())
    const [bulkWorking, setBulkWorking] = useState(false)
    const [sortBy, setSortBy] = useState<PlaylistSortKey>('name')
    const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('asc')
    const [filterVisibility, setFilterVisibility] = useState<string>('')

    const {data: playlists = []} = useQuery<Playlist[]>({
        queryKey: ['admin-playlists'],
        queryFn: async () => {
            const res = await adminApi.listAllPlaylists()
            return res.items
        },
    })

    const {data: playlistStats} = useQuery<AdminPlaylistStats>({
        queryKey: ['admin-playlist-stats'],
        queryFn: () => adminApi.getPlaylistStats(),
    })

    async function handleDelete(id: string, name: string) {
        if (!window.confirm(`Delete playlist "${name}"?`)) return
        try {
            await adminApi.deletePlaylist(id)
            setMsg({type: 'success', text: `Playlist "${name}" deleted.`})
            await queryClient.invalidateQueries({queryKey: ['admin-playlists']})
            await queryClient.invalidateQueries({queryKey: ['admin-playlist-stats']})
        } catch (err) {
            setMsg({type: 'error', text: errMsg(err)})
        }
    }

    async function handleBulkDelete() {
        if (selected.size === 0) return
        if (!window.confirm(`Delete ${selected.size} playlist(s)? This cannot be undone.`)) return
        setBulkWorking(true)
        setMsg(null)
        try {
            const result = await adminApi.bulkDeletePlaylists([...selected])
            setSelected(new Set())
            await queryClient.invalidateQueries({queryKey: ['admin-playlists']})
            await queryClient.invalidateQueries({queryKey: ['admin-playlist-stats']})
            setMsg({
                type: result.failed > 0 ? 'error' : 'success',
                text: `Deleted ${result.success} playlist(s)${result.failed > 0 ? `, ${result.failed} failed` : ''}.`
            })
        } catch (err) {
            setMsg({type: 'error', text: errMsg(err)})
        } finally {
            setBulkWorking(false)
        }
    }

    const filtered = playlists.filter(p => {
        if (search && !p.name.toLowerCase().includes(search.toLowerCase()) && !p.user_id.toLowerCase().includes(search.toLowerCase())) return false
        if (filterVisibility === 'public' && !p.is_public) return false
        return !(filterVisibility === 'private' && p.is_public)
    }).sort((a, b) => {
        let cmp = 0
        switch (sortBy) {
            case 'name': cmp = a.name.localeCompare(b.name); break
            case 'user_id': cmp = a.user_id.localeCompare(b.user_id); break
            case 'items': cmp = (a.items?.length ?? 0) - (b.items?.length ?? 0); break
            case 'is_public':
                if (a.is_public !== b.is_public) cmp = a.is_public ? -1 : 1
                break
            case 'created_at': cmp = a.created_at.localeCompare(b.created_at); break
        }
        return sortOrder === 'desc' ? -cmp : cmp
    })

    const allSelected = filtered.length > 0 && filtered.every(p => selected.has(p.id))

    function handleSort(column: PlaylistSortKey) {
        if (sortBy === column) setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc')
        else { setSortBy(column); setSortOrder('asc') }
    }

    function sortIndicator(column: PlaylistSortKey) {
        if (sortBy !== column) return <span style={{opacity: 0.3, marginLeft: 4}}>&#x21C5;</span>
        const arrow = sortOrder === 'asc' ? '\u25B2' : '\u25BC'
        return <span style={{marginLeft: 4}}>{arrow}</span>
    }

    function toggleSelectAll() {
        if (allSelected) {
            setSelected(prev => {
                const next = new Set(prev);
                filtered.forEach(p => next.delete(p.id));
                return next
            })
        } else {
            setSelected(prev => {
                const next = new Set(prev);
                filtered.forEach(p => next.add(p.id));
                return next
            })
        }
    }

    const selectStyle: React.CSSProperties = {
        padding: '6px 10px', border: '1px solid var(--border-color)', borderRadius: 6,
        background: 'var(--input-bg)', color: 'var(--text-color)', fontSize: 13,
    }
    const thSortStyle: React.CSSProperties = {cursor: 'pointer', userSelect: 'none', whiteSpace: 'nowrap'}

    return (
        <div>
            {msg && <div
                className={`admin-alert admin-alert-${msg.type === 'success' ? 'success' : 'danger'}`}>{msg.text}</div>}
            {playlistStats && (
                <div className="admin-stats-grid" style={{marginBottom: 16}}>
                    <div className="admin-stat-card">
                        <span className="admin-stat-value">{playlistStats.total_playlists.toLocaleString()}</span>
                        <span className="admin-stat-label">Total Playlists</span>
                    </div>
                    <div className="admin-stat-card">
                        <span className="admin-stat-value">{playlistStats.total_items.toLocaleString()}</span>
                        <span className="admin-stat-label">Total Items</span>
                    </div>
                    <div className="admin-stat-card">
                        <span className="admin-stat-value">{playlistStats.public_playlists.toLocaleString()}</span>
                        <span className="admin-stat-label">Public Playlists</span>
                    </div>
                </div>
            )}
            <div className="admin-card">
                <div style={{display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap', alignItems: 'center'}}>
                    <input
                        type="search"
                        placeholder="Search playlists..."
                        value={search}
                        onChange={e => { setSearch(e.target.value); }}
                        style={{...selectStyle, flex: 1, minWidth: 160}}
                    />
                    <select value={filterVisibility} onChange={e => { setFilterVisibility(e.target.value); }} style={selectStyle}>
                        <option value="">All Visibility</option>
                        <option value="public">Public Only</option>
                        <option value="private">Private Only</option>
                    </select>
                    {(search || filterVisibility) && (
                        <button className="admin-btn" style={{fontSize: 12, padding: '4px 10px'}}
                                onClick={() => { setSearch(''); setFilterVisibility('') }}>
                            <i className="bi bi-x-circle"/> Clear
                        </button>
                    )}
                    <span style={{fontSize: 12, color: 'var(--text-muted)'}}>
                        {filtered.length} of {playlists.length} playlist{playlists.length !== 1 ? 's' : ''}
                    </span>
                </div>
                {selected.size > 0 && (
                    <div style={{
                        marginBottom: 10, padding: '8px 12px', background: 'var(--hover-bg)',
                        border: '1px solid var(--border-color)', borderRadius: 6,
                        display: 'flex', gap: 8, alignItems: 'center',
                    }}>
                        <span style={{
                            fontSize: 13,
                            fontWeight: 600,
                            color: 'var(--accent-color)'
                        }}>{selected.size} selected</span>
                        <button className="admin-btn admin-btn-danger" onClick={handleBulkDelete} disabled={bulkWorking}
                                style={{fontSize: 12, padding: '4px 10px'}}>
                            <i className="bi bi-trash-fill"/> Delete Selected
                        </button>
                        <button className="admin-btn" onClick={() => { setSelected(new Set()); }}
                                style={{fontSize: 12, padding: '4px 10px'}}>Clear
                        </button>
                    </div>
                )}
                <div className="admin-table-wrapper">
                    <table className="admin-table">
                        <thead>
                        <tr>
                            <th style={{width: 32}}>
                                <input type="checkbox" checked={allSelected} onChange={toggleSelectAll}/>
                            </th>
                            {PLAYLIST_SORT_COLUMNS.map(col => (
                                <th key={col.key} style={thSortStyle} onClick={() => { handleSort(col.key); }}>
                                    {col.label}{sortIndicator(col.key)}
                                </th>
                            ))}
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {filtered.length === 0 ? (
                            <tr>
                                <td colSpan={PLAYLIST_SORT_COLUMNS.length + 2} style={{textAlign: 'center', color: 'var(--text-muted)'}}>No playlists
                                    found
                                </td>
                            </tr>
                        ) : filtered.map(pl => (
                            <tr key={pl.id}
                                style={selected.has(pl.id) ? {background: 'color-mix(in srgb, var(--accent-color) 8%, transparent)'} : undefined}>
                                <td>
                                    <input type="checkbox" checked={selected.has(pl.id)}
                                           onChange={() => setSelected(prev => {
                                               const next = new Set(prev)
                                               if (next.has(pl.id)) next.delete(pl.id)
                                               else next.add(pl.id)
                                               return next
                                           })}/>
                                </td>
                                <td>{pl.name}</td>
                                <td style={{fontSize: 12, color: 'var(--text-muted)'}}>{pl.user_id}</td>
                                <td>{pl.items?.length ?? 0}</td>
                                <td>{pl.is_public ? 'Yes' : 'No'}</td>
                                <td style={{
                                    fontSize: 12,
                                    color: 'var(--text-muted)'
                                }}>{new Date(pl.created_at).toLocaleDateString()}</td>
                                <td>
                                    <button className="admin-btn admin-btn-danger" style={{padding: '3px 8px'}}
                                            onClick={() => handleDelete(pl.id, pl.name)}>
                                        <i className="bi bi-trash-fill"/>
                                    </button>
                                </td>
                            </tr>
                        ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    )
}

// web/nuxt-ui/components/admin/PlaylistsTab.vue
<script setup lang="ts">
import type { Playlist, AdminPlaylistStats } from '~/types/api'

const adminApi = useAdminApi()
const toast = useToast()

const playlists = ref<Playlist[]>([])
const loading = ref(true)
const deleteTarget = ref<Playlist | null>(null)
const deleting = ref(false)
const stats = ref<AdminPlaylistStats | null>(null)

// Search, filter, sort, pagination
const search = ref('')
const visibilityFilter = ref<'all' | 'public' | 'private'>('all')
const sortKey = ref<'name' | 'user_id' | 'items' | 'is_public' | 'created_at'>('name')
const sortDir = ref<'asc' | 'desc'>('asc')
const page = ref(1)
const perPage = ref(25)

const PER_PAGE_OPTIONS = [
  { label: '25', value: 25 },
  { label: '50', value: 50 },
  { label: '100', value: 100 },
]

function doSort(key: typeof sortKey.value) {
  if (sortKey.value === key) {
    sortDir.value = sortDir.value === 'asc' ? 'desc' : 'asc'
  } else {
    sortKey.value = key
    sortDir.value = 'asc'
  }
}

function sortIndicator(key: string) {
  if (sortKey.value !== key) return ''
  return sortDir.value === 'asc' ? ' \u2191' : ' \u2193'
}

const filtered = computed(() => {
  let result = playlists.value
  if (search.value) {
    const q = search.value.toLowerCase()
    result = result.filter(p =>
      p.name.toLowerCase().includes(q) || (p.user_id ?? '').toLowerCase().includes(q),
    )
  }
  if (visibilityFilter.value === 'public') result = result.filter(p => p.is_public)
  else if (visibilityFilter.value === 'private') result = result.filter(p => !p.is_public)

  result = [...result].sort((a, b) => {
    let cmp = 0
    switch (sortKey.value) {
      case 'name': cmp = a.name.localeCompare(b.name); break
      case 'user_id': cmp = (a.user_id ?? '').localeCompare(b.user_id ?? ''); break
      case 'items': cmp = (a.items?.length ?? 0) - (b.items?.length ?? 0); break
      case 'is_public': cmp = Number(a.is_public) - Number(b.is_public); break
      case 'created_at': cmp = (a.created_at ?? '').localeCompare(b.created_at ?? ''); break
    }
    return sortDir.value === 'asc' ? cmp : -cmp
  })
  return result
})

const totalFiltered = computed(() => filtered.value.length)
const totalPages = computed(() => Math.max(1, Math.ceil(totalFiltered.value / perPage.value)))
const paged = computed(() => {
  const start = (page.value - 1) * perPage.value
  return filtered.value.slice(start, start + perPage.value)
})

watch([search, visibilityFilter, sortKey, sortDir, perPage], () => { page.value = 1 })

// Bulk selection
const selected = ref<Set<string>>(new Set())
const bulkDeleting = ref(false)
const allSelected = computed(() => paged.value.length > 0 && paged.value.every(p => selected.value.has(p.id)))

function toggleSelect(id: string) {
  const s = new Set(selected.value)
  s.has(id) ? s.delete(id) : s.add(id)
  selected.value = s
}

function toggleAll() {
  if (allSelected.value) {
    selected.value = new Set()
  } else {
    selected.value = new Set(paged.value.map(p => p.id))
  }
}

async function bulkDelete() {
  if (!selected.value.size) return
  bulkDeleting.value = true
  try {
    const ids = Array.from(selected.value)
    const res = await adminApi.bulkDeletePlaylists(ids)
    toast.add({ title: `Deleted ${res.success} playlist${res.success !== 1 ? 's' : ''}${res.failed ? `, ${res.failed} failed` : ''}`, color: res.failed ? 'warning' : 'success', icon: 'i-lucide-check' })
    selected.value = new Set()
    await load()
  } catch (e: unknown) {
    toast.add({ title: e instanceof Error ? e.message : 'Bulk delete failed', color: 'error', icon: 'i-lucide-x' })
  } finally { bulkDeleting.value = false }
}

async function load() {
  loading.value = true
  try {
    const [res, s] = await Promise.allSettled([
      adminApi.listAllPlaylists(),
      adminApi.getPlaylistStats(),
    ])
    if (res.status === 'fulfilled') {
      playlists.value = Array.isArray(res.value) ? res.value : (res.value?.items ?? [])
    }
    if (s.status === 'fulfilled') stats.value = s.value
  } catch (e: unknown) {
    toast.add({ title: e instanceof Error ? e.message : 'Failed to load playlists', color: 'error', icon: 'i-lucide-alert-circle' })
  } finally { loading.value = false }
}

async function handleDelete() {
  if (!deleteTarget.value) return
  deleting.value = true
  try {
    await adminApi.deletePlaylist(deleteTarget.value.id)
    toast.add({ title: 'Playlist deleted', color: 'success', icon: 'i-lucide-check' })
    deleteTarget.value = null
    await load()
  } catch (e: unknown) {
    toast.add({ title: e instanceof Error ? e.message : 'Failed', color: 'error', icon: 'i-lucide-x' })
  } finally {
    deleting.value = false
  }
}

onMounted(load)
</script>

<template>
  <div class="space-y-4">
    <!-- Stats banner -->
    <div class="grid grid-cols-3 gap-3">
      <UCard :ui="{ body: 'p-3' }">
        <p class="text-xl font-bold text-highlighted">{{ stats?.total_playlists ?? playlists.length }}</p>
        <p class="text-xs text-muted mt-1">Total Playlists</p>
      </UCard>
      <UCard :ui="{ body: 'p-3' }">
        <p class="text-xl font-bold text-highlighted">{{ stats?.public_playlists ?? playlists.filter(p => p.is_public).length }}</p>
        <p class="text-xs text-muted mt-1">Public</p>
      </UCard>
      <UCard :ui="{ body: 'p-3' }">
        <p class="text-xl font-bold text-highlighted">{{ stats?.total_items ?? playlists.reduce((s, p) => s + (p.items?.length ?? 0), 0) }}</p>
        <p class="text-xs text-muted mt-1">Total Items</p>
      </UCard>
    </div>

    <!-- Toolbar: search, filter, per-page -->
    <div class="flex flex-wrap gap-2 items-center justify-between">
      <div class="flex flex-wrap gap-2 items-center">
        <UInput
          v-model="search"
          icon="i-lucide-search"
          placeholder="Search name or owner…"
          class="w-56"
        />
        <USelect
          v-model="visibilityFilter"
          :items="[
            { label: 'All Visibility', value: 'all' },
            { label: 'Public', value: 'public' },
            { label: 'Private', value: 'private' },
          ]"
          class="w-40"
        />
        <USelect
          v-model="perPage"
          :items="PER_PAGE_OPTIONS"
          class="w-24"
        />
      </div>
      <div class="flex gap-2 items-center">
        <UButton
          v-if="selected.size > 0"
          :loading="bulkDeleting"
          icon="i-lucide-trash-2"
          :label="`Delete Selected (${selected.size})`"
          color="error"
          variant="outline"
          size="sm"
          @click="bulkDelete"
        />
        <span class="text-sm text-muted">{{ totalFiltered }} playlist{{ totalFiltered !== 1 ? 's' : '' }}</span>
        <UButton icon="i-lucide-refresh-cw" aria-label="Refresh playlists" variant="ghost" color="neutral" @click="load" />
      </div>
    </div>

    <UCard>
      <div v-if="loading" class="flex justify-center py-8">
        <UIcon name="i-lucide-loader-2" class="animate-spin size-6" />
      </div>
      <div v-else class="overflow-x-auto">
        <table class="min-w-full text-sm">
          <thead>
            <tr class="border-b border-default text-left text-xs text-muted">
              <th class="px-3 py-2 w-8">
                <UCheckbox :model-value="allSelected" @update:model-value="toggleAll" />
              </th>
              <th class="px-3 py-2 cursor-pointer hover:text-default select-none" @click="doSort('name')">
                Name{{ sortIndicator('name') }}
              </th>
              <th class="px-3 py-2 cursor-pointer hover:text-default select-none" @click="doSort('user_id')">
                Owner{{ sortIndicator('user_id') }}
              </th>
              <th class="px-3 py-2 cursor-pointer hover:text-default select-none text-right" @click="doSort('items')">
                Items{{ sortIndicator('items') }}
              </th>
              <th class="px-3 py-2 cursor-pointer hover:text-default select-none" @click="doSort('is_public')">
                Visibility{{ sortIndicator('is_public') }}
              </th>
              <th class="px-3 py-2 cursor-pointer hover:text-default select-none" @click="doSort('created_at')">
                Created{{ sortIndicator('created_at') }}
              </th>
              <th class="px-3 py-2 w-10" />
            </tr>
          </thead>
          <tbody class="divide-y divide-default">
            <tr v-for="p in paged" :key="p.id" class="hover:bg-muted/30">
              <td class="px-3 py-2">
                <UCheckbox :model-value="selected.has(p.id)" @update:model-value="toggleSelect(p.id)" />
              </td>
              <td class="px-3 py-2">
                <div>
                  <p class="font-medium">{{ p.name }}</p>
                  <p v-if="p.description" class="text-xs text-muted truncate max-w-xs">{{ p.description }}</p>
                </div>
              </td>
              <td class="px-3 py-2 font-mono text-xs">{{ p.user_id?.slice(0, 8) }}…</td>
              <td class="px-3 py-2 text-right">{{ p.items?.length ?? 0 }}</td>
              <td class="px-3 py-2">
                <UBadge
                  :label="p.is_public ? 'Public' : 'Private'"
                  :color="p.is_public ? 'success' : 'neutral'"
                  variant="subtle"
                  size="xs"
                />
              </td>
              <td class="px-3 py-2 text-muted">
                {{ p.created_at ? new Date(p.created_at).toLocaleDateString() : '—' }}
              </td>
              <td class="px-3 py-2 text-right">
                <UButton
                  icon="i-lucide-trash-2"
                  size="xs"
                  variant="ghost"
                  color="error"
                  @click="deleteTarget = p"
                />
              </td>
            </tr>
          </tbody>
        </table>
        <p v-if="paged.length === 0" class="text-center py-6 text-muted text-sm">
          No playlists found.
        </p>
      </div>
    </UCard>

    <!-- Pagination -->
    <div v-if="totalPages > 1" class="flex justify-center">
      <UPagination
        v-model:page="page"
        :total="totalFiltered"
        :items-per-page="perPage"
      />
    </div>

    <!-- Delete confirmation -->
    <UModal
      v-if="deleteTarget"
      :open="!!deleteTarget"
      title="Delete Playlist"
      @update:open="val => { if (!val) deleteTarget = null }"
    >
      <template #body>
        Are you sure you want to delete <strong>{{ deleteTarget?.name }}</strong>? This cannot be undone.
      </template>
      <template #footer>
        <UButton variant="ghost" color="neutral" label="Cancel" @click="deleteTarget = null" />
        <UButton :loading="deleting" color="error" label="Delete" @click="handleDelete" />
      </template>
    </UModal>
  </div>
</template>
